from mutator.mutator import mutate
import pytest


def test_basic():
    sequences = {'reference': 'aaaacczfff',
                 'other_one': 'bc',
                 'other_three': 'ggg'}

    variants = [
        {'type': 'deletion_insertion',
         'source': 'reference',
         'location': {'type': 'range',
                      'start': {'type': 'point',
                                'position': 3},
                      'end': {'type': 'point',
                              'position': 4}},
         'inserted': [{'source': 'description',
                       'sequence': 'bb'}]},
        {'type': 'deletion_insertion',
         'source': 'reference',
         'location': {'type': 'range',
                      'start': {'type': 'point',
                                'position': 4},
                      'end': {'type': 'point',
                              'position': 4}},
         'inserted': [{'source': 'other_one',
                       'location': {'type': 'range',
                                    'start': {'type': 'point',
                                              'position': 0},
                                    'end': {'type': 'point',
                                            'position': 10}}}]},
        {'type': 'deletion_insertion',
         'source': 'reference',
         'location': {'type': 'range',
                      'start': {'type': 'point',
                                'position': 6},
                      'end': {'type': 'point',
                              'position': 7}},
         'inserted': []},
        {'type': 'deletion_insertion',
         'source': 'reference',
         'location': {'type': 'range',
                      'start': {'type': 'point',
                                'position': 7},
                      'end': {'type': 'point',
                              'position': 7}},
         'inserted': [{'source': 'description',
                       'sequence': 'ddd'}]},
        {'type': 'deletion_insertion',
         'source': 'reference',
         'location': {'type': 'range',
                      'start': {'type': 'point',
                                'position': 8},
                      'end': {'type': 'point',
                              'position': 9}},
         'inserted': [{'source': 'description',
                       'sequence': 'ggg'}]},
        {'type': 'deletion_insertion',
         'source': 'reference',
         'location': {'type': 'range',
                      'start': {'type': 'point',
                                'position': 9},
                      'end': {'type': 'point',
                              'position': 10}},
         'inserted': [{'source': 'description',
                       'sequence': 'hhh'}]}]

    assert mutate(sequences, variants) == 'aaabbbcccdddfggghhh'


REFERENCE = 'ACGTCGATTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT'

TESTS = [
    ('(empty)',
     {'reference': '',
      'observed': ''},
     []),

    ('=',
     {'reference': REFERENCE,
      'observed': REFERENCE},
     []),

    ('7A>G',
     {'reference': REFERENCE,
      'observed': 'ACGTCGGTTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT'},
     [{'type': 'deletion_insertion',
       'location': {'type': 'range',
                    'end': {'position': 7,
                            'type': 'point'},
                    'start': {'position': 6,
                              'type': 'point'}},
       'inserted': [{'source': 'observed',
                     'location': {'type': 'range',
                                  'end': {'position': 7,
                                          'type': 'point'},
                                  'start': {'position': 6,
                                            'type': 'point'}}}]}]),

    ('7del',
     {'reference': REFERENCE,
      'observed': 'ACGTCGTTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT'},
     [{'type': 'deletion_insertion',
       'source': 'reference',
       'location': {'type': 'range',
                    'start': {'position': 6,
                              'type': 'point'},
                    'end': {'position': 7,
                            'type':'point'}},
       'inserted':[{'source': 'observed',
                    'location': {'type': 'range',
                                 'start': {'position': 6,
                                           'type': 'point'},
                                 'end': {'position': 6,
                                         'type': 'point'}}}]}]),

    ('7_8del',
     {'reference': REFERENCE,
      'observed': 'ACGTCGTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT'},
     [{'type': 'deletion_insertion',
       'inserted': [{'source': 'observed',
                     'location': {'type': 'range',
                                  'end': {'position': 6,
                                          'type': 'point'},
                                  'start': {'position': 6,
                                            'type': 'point'}}}],
       'source': 'reference',
       'location': {'type': 'range',
                    'end': {'position': 8,
                            'type': 'point'},
                    'start': {'position': 6,
                              'type': 'point'}}}]),

    ('6_7insC',
     {'reference': REFERENCE,
      'observed': 'ACGTCGCATTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT'},
     [{'type': 'deletion_insertion',
       'source': 'reference',
       'location': {'type': 'range',
                    'start': {'position': 6,
                              'type': 'point'},
                    'end': {'position': 6, 'type': 'point'}},
       'inserted': [{'source': 'observed',
                     'location': {'type': 'range',
                                  'start': {'position': 6,
                                            'type': 'point'},
                                  'end': {'position': 7,
                                          'type': 'point'}}}]}]),

    ('[26A>C;30C>A;35G>C]',
     {'reference': 'TAAGCACCAGGAGTCCATGAAGAAGATGGCTCCTGCCATGGAATCCCCTACTCTACTGTG',
      'observed': 'TAAGCACCAGGAGTCCATGAAGAAGCTGGATCCTCCCATGGAATCCCCTACTCTACTGTG'},
     [{'type': 'deletion_insertion',
       'source': 'reference',
       'location': {'end': {'position': 26,
                            'type': 'point'},
                    'type': 'range',
                    'start': {'position': 25,
                              'type': 'point'}},
       'inserted': [{'source': 'observed',
                     'location': {'end': {'position': 26,
                                          'type': 'point'},
                                  'type': 'range',
                                  'start': {'position': 25,
                                            'type': 'point'}}}]},
      {'type': 'deletion_insertion',
       'source': 'reference',
       'location': {'end': {'position': 30,
                            'type': 'point'},
                    'type': 'range',
                    'start': {'position': 29,
                              'type': 'point'}},
       'inserted': [{'source':'observed',
                     'location': {'end': {'position': 30,
                                          'type': 'point'},
                                  'type': 'range',
                                  'start': {'position': 29,
                                            'type': 'point'}}}]},
      {'type': 'deletion_insertion',
       'source': 'reference',
       'location': {'end': {'position': 35,
                            'type': 'point'},
                    'type': 'range',
                    'start': {'position': 34,
                              'type': 'point'}},
       'inserted': [{'source': 'observed',
                     'location': {'end': {'position': 35,
                                          'type': 'point'},
                                  'type': 'range',
                                  'start': {'position': 34,
                                            'type': 'point'}}}]},
      ]),

    ('37_38ins3_26inv',
     {'reference': 'ATGGCGGCGGTGGTCGCCCTCTCCTTGAGGCGCCGGTTGCCGGCCACAACCCTTGGCGGA',
      'observed':  'ATGGCGGCGGTGGTCGCCCTCTCCTTGAGGCGCCGGTAAGGAGAGGGCGACCACCGCCGCCTGCCGGCCACAACCCTTGGCGGA'},
     [{'type': 'deletion_insertion',
       'source': 'reference',
       'location': {'end': {'position': 37,
                            'type': 'point'},
                    'type': 'range',
                    'start': {'position': 37,
                              'type': 'point'}},
       'inserted': [{'source': 'reference',

                     'location': {'type': 'range',
                                  'start': {'position': 2,
                                            'type': 'point'},
                                  'end': {'position': 26,
                                          'type': 'point'}},
                     'inverted': True}]}]),

]


@pytest.mark.parametrize('_, sequences, variants', TESTS)
def test_variants_de_extracts(_, sequences, variants):
    assert sequences['observed'] == mutate(sequences, variants)
